const IconsImagesObj = {
  chanceflurries: 'lib/icons/chanceflurries.svg',
  chancerain: 'lib/icons/chancerain.svg',
  chancesleet: 'lib/icons/chancesleet.svg',
  chancesnow: 'lib/icons/chancesnow.svg',
  chancetstorms: 'lib/icons/chancetstorms.svg',
  cloudyDay: 'lib/icons/cloudyDay.svg',
  cloudyNight: 'lib/icons/cloudyNight.svg',
  cloudy: 'lib/icons/cloudy.svg',
  clear: 'lib/icons/clear.svg',
  flurries: 'lib/icons/snow.svg',
  fog: 'lib/icons/fog.svg',
  mostlycloudy: 'lib/icons/mostlycloudy.svg',
  partlycloudy: 'lib/icons/partlycloudy.svg',
  rain: 'lib/icons/rain.svg',
  showering: 'lib/icons/showering.svg',
  sleet: 'lib/icons/sleet.svg',
  snow: 'lib/icons/snow.svg',
  sunny: 'lib/icons/sun.svg',
  tstorms: 'lib/icons/tstorms.svg',
  windy: 'lib/icons/windy.svg',
  nt_chanceflurries: 'lib/icons/nt_chanceflurries.svg',
  nt_chancerain: 'lib/icons/nt_chancerain.svg',
  nt_chancesleet: 'lib/icons/nt_chancesleet.svg',
  nt_chancesnow: 'lib/icons/nt_chancesnow.svg',
  nt_chancetstorms: 'lib/icons/nt_chancetstorms.svg',
  nt_clear: 'lib/icons/nt_clear.svg',
  nt_cloudy: 'lib/icons/nt_cloudy.svg',
  nt_flurries: 'lib/icons/nt_flurries.svg',
  nt_fog: 'lib/icons/nt_fog.svg',
  nt_hazy: 'lib/icons/nt_hazy.svg',
  nt_mostlycloudy: 'lib/icons/nt_mostlycloudy.svg',
  nt_mostlysunny: 'lib/icons/nt_mostlysunny.svg',
  nt_partlycloudy: 'lib/icons/nt_partlycloudy.svg',
  nt_partlysunny: 'lib/icons/nt_partlysunny.svg',
  nt_rain: 'lib/icons/nt_rain.svg',
  nt_sleet: 'lib/icons/nt_sleet.svg',
  nt_snow: 'lib/icons/nt_snow.svg',
  nt_sunny: 'lib/icons/nt_sunny.svg',
  nt_tstorms: 'lib/icons/nt_tstorms.svg',





  cloudyDayImage: 'lib/images/cloudDay.jpg',
  cloudyNightImage: 'lib/images/cloudyNight.jpg',
  cloudyImage: 'lib/images/cloudy.png',
  clearImage: 'lib/images/clear.png',
  rainImage: 'lib/images/rain.png',
  showeringImage: 'lib/images/showeringImage.jpg',
  snowImage: 'lib/images/snow.png',
  sunnyImage: 'lib/images/sunny.png',
  tstormsImage: 'lib/images/tstorms.png',
  windyImage: 'lib/images/windy.jpg',
  mostlycloudyImage: 'lib/images/mostlycloudy.png',
  partlycloudyImage: 'lib/images/partlycloudy.png',
  flurriesImage: 'lib/images/snow.png',
  fogImage: '',
};

export default IconsImagesObj;
